<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Breadboard.Infra.COPS</AssemblyName>
		<RootNamespace>Breadboard.Infra.COPS</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Application\Breadboard.Application\Breadboard.Application.csproj" />
		<ProjectReference Include="..\..\Domain\Breadboard.Shared\Breadboard.Shared.csproj" />
	</ItemGroup>

</Project>
