<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Breadboard.Application\Breadboard.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
