<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Breadboard.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
        <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Modules\Users\Users.Domain\Users.Domain.csproj" />
    </ItemGroup>
</Project>
