<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Breadboard.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Breadboard.Domain.Shared\Breadboard.Domain.Shared.csproj"/>
    </ItemGroup>

</Project>
