<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Breadboard.Presentation</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.7" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.Jwt\BuildingBlocks.Jwt.csproj" />
      <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.PostgreSQLDapper\BuildingBlocks.PostgreSQLDapper.csproj" />
      <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.PostgreSQL\BuildingBlocks.PostgreSQL.csproj" />
      <ProjectReference Include="..\..\Modules\Finances\Finances.Presentation\Finances.Presentation.csproj" />
      <ProjectReference Include="..\..\Modules\Orders\Orders.Presentation\Orders.Presentation.csproj" />
      <ProjectReference Include="..\..\Modules\Products\Products.Presentation\Products.Presentation.csproj" />
      <ProjectReference Include="..\..\Modules\Users\Users.Infrastructure\Users.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Modules\Users\Users.Presentation\Users.Presentation.csproj" />
      <ProjectReference Include="..\Breadboard.Infra.Jwt\BuildingBlocks.Jwt.csproj" />
    </ItemGroup>

</Project>



