<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Application\Breadboard.Application.Shared\Breadboard.Application.Shared.csproj"/>
        <ProjectReference Include="..\..\Application\Breadboard.Application.Users\Breadboard.Application.Users.csproj" />
        <ProjectReference Include="..\..\Domain\Breadboard.Domain.Users\Breadboard.Domain.Users.csproj" />
        <ProjectReference Include="..\..\Domain\Breadboard.Domain.Shared\Breadboard.Domain.Shared.csproj" />
    </ItemGroup>

</Project>