<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Expenses\Commands\" />
    <Folder Include="Expenses\Services\" />
    <Folder Include="Roles\" />
    <Folder Include="UserRoles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Breadboard.Shared\Breadboard.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Riok.Mapperly" Version="5.0.0-next.0" />
  </ItemGroup>

</Project>
